name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npx update-browserslist-db@latest

      - name: Build Chrome 
        run: npm run build || npm run build

      - name: Build Firefox
        run: npm run build:firefox || npm run build:firefox

      - name: Package Chrome artifacts
        run: |
          cd dist
          # Chrome
          zip -r ../my-fingerprint-chrome-${{ github.ref_name }}.zip .
          # Chrome Webstore
          jq 'del(.key, .update_url)' manifest.json > manifest.tmp.json && mv manifest.tmp.json manifest.json
          zip -r ../my-fingerprint-chrome-webstore-${{ github.ref_name }}.zip .
          cd ..

      - name: Package Firefox artifacts
        run: |
          cd dist-firefox && zip -r ../my-fingerprint-firefox-${{ github.ref_name }}.zip . && cd ..

      - name: Upload internal artifacts
        uses: actions/upload-artifact@v4
        with:
          name: store-uploads
          path: |
            my-fingerprint-chrome-webstore-${{ github.ref_name }}.zip
            my-fingerprint-firefox-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          files: |
            my-fingerprint-chrome-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
